version: '3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: test-fullstack-frontend
    ports:
      - "3000:3000"
    volumes:
      - ./Nginx/default.conf:/etc/Nginx/conf.d/default.conf
